@vite([
        'resources/vendors/mdi/css/materialdesignicons.min.css', 
        'resources/vendors/ti-icons/css/themify-icons.css', 
        'resources/vendors/css/vendor.bundle.base.css', 
        'resources/vendors/font-awesome/css/font-awesome.min.css', 
        'resources/vendors/bootstrap-datepicker/bootstrap-datepicker.min.css', 
        'resources/css/style.css', 
        'resources/vendors/js/vendor.bundle.base.js',
        'resources/js/off-canvas.js',
        'resources/js/misc.js',
        'resources/js/settings.js',
        'resources/js/todolist.js',
        'resources/js/jquery.cookie.js',
        'resources/js/bootstrap.js']) 